Repository WebAssembly/simd, pull requests merged in 2021-02, with the labels that each got.

#383 Double-precision conversion instructions
  proposals/simd/BinarySIMD.md
  proposals/simd/ImplementationStatus.md
  proposals/simd/SIMD.md
Labels: 2021-01-29

#434 Run simd test cases with make partest
  interpreter/Makefile
Labels: tracking

#440 [interpreter] Add i64x2.eq and i64x2.ne
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_i64x2_cmp.py
  test/core/simd/simd_i64x2_cmp.wast
Labels: interpreter

#439 [spectext] Add semantics for v128.load32_zero v128.load64_zero
  document/core/binary/instructions.rst
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
  document/core/valid/instructions.rst
Labels: spectext

#438 [interpreter] Implement SIMD extended multiply instructions
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/simd.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_arithmetic.py
  test/core/simd/meta/simd_ext_mul.py
  test/core/simd/meta/simd_integer_op.py
  test/core/simd/simd_i16x8_extmul_i8x16.wast
  test/core/simd/simd_i32x4_extmul_i16x8.wast
  test/core/simd/simd_i64x2_extmul_i32x4.wast
Labels: interpreter

#444 [spectext] Add i64x2.all_true
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#422 Implement i64x2.bitmask (#368)
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/simd_boolean.wast
Labels: interpreter

#412 i64x2.gt_s, i64x2.lt_s, i64x2.ge_s, and i64x2.le_s instructions
  proposals/simd/BinarySIMD.md
  proposals/simd/ImplementationStatus.md
  proposals/simd/SIMD.md
Labels: needs discussion

#413 i64x2.abs instruction
  proposals/simd/BinarySIMD.md
  proposals/simd/ImplementationStatus.md
  proposals/simd/NewOpcodes.md
  proposals/simd/SIMD.md
Labels: needs discussion

#453 [spectext] Add ext mul instructions
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/util/macros.def
  document/core/valid/instructions.rst
Labels: spectext

#450 [spectext] Add i8x16.popcnt to syntax
  document/core/syntax/instructions.rst
  document/core/util/macros.def
Labels: spectext

#447 [spectext] Add i64x2.widen_{low,high}_i32x4_{s,u} to syntax
  document/core/syntax/instructions.rst
Labels: spectext

#445 [spectext] Load lane and store lane validation and semantics
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/util/macros.def
  document/core/valid/instructions.rst
Labels: spectext

#446 [interpreter] Implement i64x2.widen_{low,high}_i32x4_{s,u}
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_arithmetic.py
  test/core/simd/meta/simd_int_to_int_widen.py
  test/core/simd/simd_conversions.wast
  test/core/simd/simd_int_to_int_widen.wast
Labels: interpreter

#451 [interpreter] Implement i8x16.popcnt
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/int.ml
  interpreter/exec/simd.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/simd_int_arith2.py
  test/core/simd/meta/simd_integer_op.py
  test/core/simd/simd_i8x16_arith2.wast
Labels: interpreter

#454 [interpreter] Add i64x2 signed comparisons
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/simd_i64x2_cmp.py
  test/core/simd/simd_i64x2_cmp.wast
Labels: interpreter

#462 [interpreter] Implement i64x2.abs
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/simd_int_arith2.py
  test/core/simd/simd_i16x8_arith2.wast
Labels: interpreter

#460 [spectext] Add i64x2 widen instructions to text and binary
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#461 [spectext] Add i8x16.popcnt to text and binary format
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#457 [spectext] Add i64x2.abs
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#458 [spectext] Add i64x2 comparisons to text and binary format
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#459 [spectext] Add extmul instructions to text/binary formats
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/exec/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#435 [interpreter] Implement store lane instructions
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval.ml
  interpreter/runtime/memory.ml
  interpreter/runtime/memory.mli
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  interpreter/text/parser.mly
  interpreter/valid/valid.ml
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_store_lane.py
  test/core/simd/simd_store16_lane.wast
  test/core/simd/simd_store32_lane.wast
  test/core/simd/simd_store64_lane.wast
  test/core/simd/simd_store8_lane.wast
Labels: interpreter

#464 [spectext] Add i16x8.qmulr_sat_s
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/exec/numerics.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
  document/core/util/macros.def
Labels: spectext

#463 [interpreter] Implement i16x8.qmulr_sat_s
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/int.ml
  interpreter/exec/simd.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_i16x8_q15mulr_sat_s.py
  test/core/simd/meta/simd_integer_op.py
  test/core/simd/simd_i16x8_q15mulr_sat_s.wast
Labels: interpreter

#466 [interpreter] Implement i32x4.trunc_sat_f64x2_{s,u}_zero
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/simd.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_float_op.py
  test/core/simd/meta/simd_int_trunc_sat_float.py
  test/core/simd/meta/simd_integer_op.py
  test/core/simd/simd_conversions.wast
  test/core/simd/simd_i32x4_trunc_sat_f32x4.wast
  test/core/simd/simd_i32x4_trunc_sat_f64x2.wast
Labels: interpreter

#465 [spectext] Add load/store lane text and binary format
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/text/instructions.rst
Labels: spectext

#468 [spectext] Add {f32x4,f64x2}.{pmin,pmax}
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/exec/numerics.rst
  document/core/text/instructions.rst
  document/core/util/macros.def
Labels: spectext

#469 [interpreter] Add i64x2.all_true
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/simd_boolean.wast
Labels: interpreter

#471 [interpreter] Add a missing closing parens
  interpreter/exec/simd.ml
Labels: interpreter

#472 [interpreter] f64x2.promote_low_f32x4 and f32x4.demote_f64x2_zero
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/simd.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/simd_conversions.wast
Labels: interpreter

#478 [spectext] Rename integer widen instructions to integer extend
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
  document/core/util/macros.def
  document/core/valid/instructions.rst
  proposals/simd/BinarySIMD.md
  proposals/simd/ImplementationStatus.md
  proposals/simd/NewOpcodes.md
  proposals/simd/SIMD.md
Labels: spectext

#473 [interpreter] Implement f64x2.convert_low_i32x4_{s,u}
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/simd.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/simd_conversions.wast
Labels: interpreter

#474 [interpreter] Implement extadd pairwise instructions
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/simd.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  interpreter/util/lib.ml
  interpreter/util/lib.mli
  test/core/simd/meta/README.md
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_extadd_pairwise.py
  test/core/simd/simd_i16x8_extadd_pairwise_i8x16.wast
  test/core/simd/simd_i32x4_extadd_pairwise_i16x8.wast
Labels: interpreter

#475 [spectext] Add i32x4.dot_i16x8_s
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
  document/core/util/macros.def
  document/core/valid/instructions.rst
Labels: spectext

#476 [spectext] Add extended pairwise add instructions
  document/core/appendix/gen-index-instructions.py
  document/core/binary/instructions.rst
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
  document/core/util/macros.def
  document/core/valid/instructions.rst
Labels: spectext

#481 [interpreter] Rename integer widen instructions to integer extend
  interpreter/binary/decode.ml
  interpreter/binary/encode.ml
  interpreter/exec/eval_simd.ml
  interpreter/exec/simd.ml
  interpreter/runtime/memory.ml
  interpreter/syntax/ast.ml
  interpreter/syntax/operators.ml
  interpreter/text/arrange.ml
  interpreter/text/lexer.mll
  test/core/simd/meta/gen_tests.py
  test/core/simd/meta/simd_int_to_int_extend.py
  test/core/simd/simd_conversions.wast
  test/core/simd/simd_int_to_int_extend.wast
  test/core/simd/simd_int_to_int_widen.wast
Labels: interpreter

#482 [spectext] Add double precision conversion
  document/core/appendix/gen-index-instructions.py
  document/core/appendix/index-instructions.rst
  document/core/binary/instructions.rst
  document/core/exec/instructions.rst
  document/core/syntax/instructions.rst
  document/core/text/instructions.rst
  document/core/util/macros.def
  document/core/valid/instructions.rst
Labels: spectext

#484 Fix i32x4.trunc_sat_f64x2_zero
  interpreter/exec/simd.ml
  test/core/simd/meta/simd_int_trunc_sat_float.py
  test/core/simd/simd_i32x4_trunc_sat_f64x2.wast
Labels: interpreter

#483 Fix q15 saturating mul
  interpreter/exec/int.ml
  test/core/simd/meta/simd_integer_op.py
  test/core/simd/meta/simd_lane_value.py
  test/core/simd/simd_i16x8_q15mulr_sat_s.wast
Labels: interpreter
